Name:           ros-kinetic-follow-waypoints
Version:        0.3.0
Release:        1%{?dist}
Summary:        ROS follow_waypoints package

Group:          Development/Libraries
License:        Unlicense
URL:            http://wiki.ros.org/follow_waypoints
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-move-base-msgs
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-smach
Requires:       ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-move-base-msgs
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-smach
BuildRequires:  ros-kinetic-std-msgs

%description
The follow_waypoints node will listen for waypoints given as poses and when
instructed will follow them one by one by publishing goals to move_base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Jul 14 2017 Daniel Snider <danielsnider12@gmail.com> - 0.3.0-1
- Autogenerated by Bloom

* Fri Jul 14 2017 Daniel Snider <danielsnider12@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

* Sun Jul 09 2017 Daniel Snider <danielsnider12@gmail.com> - 0.2.0-0
- Autogenerated by Bloom

